---

- hosts: asa
  remote_user: colin
  become: yes
  become_method: enable
  connection: network_cli
  

  tasks:
  - name: SHOW VERSION
    asa_command:
      commands:
        - show version
    register: version
 
  - debug: var=version.stdout_lines
 
