

---
- hosts: asa
  gather_facts: no
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: CONFIGURE SNMP
    asa_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - snmp-server enable
        - snmp-server community ansibull
        - snmp-server host inside 192.168.161.25 community ansibull
        - snmp-server contact colin@thenetwork.engineer
        - snmp-server enable traps snmp linkup linkdown coldstart authentication
        - snmp-server enable traps syslog
        - snmp-server enable traps remote-access
        - snmp-server location building 42
      save: yes
